version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservice-network

  eureka-server:
    build: ./eureka-server
    image: ravikhot/eureka-server:latest
    container_name: eureka-server
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  employee-service:
    build: ./employee-service
    image: ravikhot/employee-service:latest
    container_name: employee-service
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URL=${EUREKA_URL}
      - EMPLOYEE_DB_URL=${EMPLOYEE_DB_URL}
      - EMPLOYEE_DB_USERNAME=${EMPLOYEE_DB_USERNAME}
      - EMPLOYEE_DB_PASSWORD=${EMPLOYEE_DB_PASSWORD}
    depends_on:
      - mysql
      - eureka-server
    ports:
      - "8081:8081"
    networks:
      - microservice-network

  department-service:
    build: ./department-service
    image: ravikhot/department-service:latest
    container_name: department-service
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URL=${EUREKA_URL}
      - DEPARTMENT_DB_URL=${DEPARTMENT_DB_URL}
      - DEPARTMENT_DB_USERNAME=${DEPARTMENT_DB_USERNAME}
      - DEPARTMENT_DB_PASSWORD=${DEPARTMENT_DB_PASSWORD}
    depends_on:
      - mysql
      - eureka-server
    ports:
      - "8082:8082"
    networks:
      - microservice-network

  api-gateway:
    build: ./api-gateway
    image: ravikhot/api-gateway:latest
    container_name: api-gateway
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URL=${EUREKA_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GATEWAY_DB_URL=${GATEWAY_DB_URL}
      - GATEWAY_DB_USERNAME=${GATEWAY_DB_USERNAME}
      - GATEWAY_DB_PASSWORD=${GATEWAY_DB_PASSWORD}
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    networks:
      - microservice-network

volumes:
  mysql_data:

networks:
  microservice-network:
    driver: bridge
