server.port=8080

# JWT Secret
jwt.secret=${JWT_SECRET}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka}

# ===============================
# GATEWAY ROUTES
# ===============================

spring.cloud.gateway.routes[0].id=employee-service
spring.cloud.gateway.routes[0].uri=lb://employee-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/employee/**

spring.cloud.gateway.routes[1].id=department-service
spring.cloud.gateway.routes[1].uri=lb://department-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/department/**

# Docker DB
spring.datasource.url=${GATEWAY_DB_URL:jdbc:mysql://mysql:3306/gatewaydb}
spring.datasource.username=${GATEWAY_DB_USERNAME}
spring.datasource.password=${GATEWAY_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
